name: flutter_wallet_card_example
description: Demonstrates how to use the flutter_wallet_card plugin.
version: 2.0.0

publish_to: "none"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_wallet_card:
    path: ../

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - passes/example.pkpass
